owner: CodeForAfrica
repo: upptime

# Add your sites here
sites:
  - name: academy.Africa
    url: https://academy.africa/

  - name: africaCommons
    url: https://commons.africa/

  - name: AlertME - Kenya
    url: https://greenalert.codeforkenya.org
    icon: https://greenalert.codeforkenya.org/assets/img/favicon.ico

  - name: AlertME - Nigeria
    url: https://yamayama.codefornigeria.org
    icon: https://yamayama.codefornigeria.org/assets/img/favicon.ico

  - name: AlertME - South Africa
    url: https://greenalert.oxpeckers.org
    icon: https://greenalert.oxpeckers.org/assets/img/favicon.ico

  - name: civicSIGNAL
    url: https://civicsignal.africa
    icon: https://civicsignal.africa/static/img/logo.png

  - name: civicSIGNAL - Explorer
    url: https://explorer.civicsignal.africa
    icon: https://civicsignal.africa/static/img/logo.png

  - name: civicSIGNAL - Sources
    url: https://sources.civicsignal.africa
    icon: https://civicsignal.africa/static/img/logo.png

  - name: civicSIGNAL - Topics
    url: https://topics.civicsignal.africa
    icon: https://civicsignal.africa/static/img/logo.png

  - name: connectedAFRICA
    url: https://data.connectedafrica.net
    icon: https://investigativecenters.org/static/img/logo.jpg

  - name: DOMINION
    url: https://dominion.africa
    icon: https://dominion.africa/favicon.ico
  
  - name: GenderGap.AFRICA
    url: https://gendergap.africa/
    icon: https://gendergap.africa/images/logo-white.svg

  - name: GMMP
    url: https://app.gmmp.ngo
    icon: https://app.gmmp.ngo/static/favicon.ico

  - name: HURUGraphQL
    url: https://graphql.hurumap.org/graphiql

  - name: HURUmap
    url: https://hurumap.org
    icon: https://hurumap.org/static/img/icons/favicon.ico

  - name: HURUmap - Kenya
    url: https://kenya.hurumap.org
    icon: https://kenya.hurumap.org/static/img/logo-white.png

  - name: HURUmap - Tanzania
    url: https://tanzania.hurumap.org
    icon: https://tanzania.hurumap.org/static/img/logo-white.png

  - name: HURUmap - Nigeria
    url: https://nigeria.hurumap.org
    icon: https://nigeria.hurumap.org/static/img/logo-white.png

  - name: HURUmap - Uganda
    url: https://uganda.hurumap.org
    icon: https://uganda.hurumap.org/static/img/logo-white.png

  - name: HURUmap - Zambia
    url: https://zambia.hurumap.org
    icon: https://zambia.hurumap.org/static/img/logo-white.png

  - name: HURUmap - Zimbabwe
    url: https://zimbabwe.hurumap.org
    icon: https://zimbabwe.hurumap.org/static/img/logos/ulwazimap.png

  - name: innovateAfrica
    url: https://innovateafrica.fund/
    icon: http://innovateafrica.fund/wp-content/uploads/2016/05/White.jpg

  - name: investigateAfrica
    url: https://investigate.africa/

  - name: LivingWage.KE
    url: https://livingwage.pd.co.ke/

  - name: MAPIT
    url: https://mapit.hurumap.org
    icon: https://hurumap.org/static/img/icons/favicon.ico

  - name: MaternalFigures
    url: https://dev.maternalfigures.com/

  - name: openAFRICA
    url: https://open.africa
    icon: https://cloud.githubusercontent.com/assets/877919/14067805/7e3ff5ae-f476-11e5-88eb-059d88816232.png

  - name: outbreakAFRICA
    url: https://dev.outbreak.africa
    icon: https://dev.outbreak.africa/favicon.ico

  - name: PesaYetu
    url: https://pesayetu.pesacheck.org
    icon: https://pesayetu.pesacheck.org/static/img/pesayetu-header-logo.png

  - name: Pfca
    url: https://dev.pfca.africa/
    icon: https://dev.pfca.africa/wp-content/uploads/sites/3/2020/12/Pfca-logo-1.png

  - name: PromiseTracker
    url: https://promisetracker.dev.codeforafrica.org/

  - name: sensors.AFRICA
    url: https://sensors.africa
    icon: https://sensors.africa/favicons/green/favicon.ico

  - name: sensors.AFRICA - API
    url: https://api.sensors.africa/docs
    icon: https://sensors.africa/favicons/green/favicon.ico

  - name: sensors.AFRICA - v2Map
    url: https://v2.map.aq.sensors.africa/#4/-4.46/19.54
    icon: https://sensors.africa/favicons/green/favicon.ico

  - name: seaSensors.AFRICA - Coming Soon
    url: https://seasensors.africa/
    icon: https://seasensors.africa/images/logo-white-square.png

  - name: seaSensors.AFRICA
    url: https://alpha.seasensors.africa/
    icon: https://seasensors.africa/images/logo-white-square.png

  - name: seaSensors.AFRICA - Map
    url: https://map.seasensors.africa/
    icon: https://seasensors.africa/images/logo-white-square.png

  - name: sourceAFRICA
    url: https://sourceafrica.net

  - name: stormWatch.sensors.AFRICA- Coming Soon
    url: https://stormwatch.sensors.africa/
    icon: https://stormwatch.sensors.africa/images/logo.png

  - name: TaxClock.Kenya
    url: https://taxclock.pesacheck.org/

  - name: trafficking.Africa - Coming Soon
    url: https://trafficking.africa/

status-website:
  cname: status.codeforafrica.org
  name: CfAFRICA Upptime
  logoUrl: https://avatars0.githubusercontent.com/u/2786364?s=200&v=4
